In [1]:
import numpy as np
import tensorflow as tf
np.random.seed(0)
tf.random.set_seed(0)


In [6]:
num_inputs = 2
num_neurons = 3

#define variables for weoght matrices

Wf = tf.Variable(tf.random.normal(shape=[num_inputs, num_neurons]))

Wr = tf.Variable(tf.random.normal(shape=[num_neurons, num_neurons]))

#notice that the recurrent weights are square matrices

b = tf.Variable(tf.zeros([1,num_neurons]))

#create data
xt0_batch = np.array([[0,1], [2,3], [4,5]]).astype(np.float32)
xt1_batch = np.array([[100,101],[102,103],[104,105]]).astype(np.float32)

#define function named forward_pass

def forward_pass(xt0, xt1):
    yt0 = tf.tanh(tf.matmul(xt0, Wf) + b)
    yt1 = tf.tanh(tf.matmul(yt0, Wr)  + tf.matmul(xt1, Wf) + b)
    return yt0, yt1


In [7]:
#perform forward pass

yt0_output, yt1_output = forward_pass(xt0_batch, xt1_batch)
tf.print(yt0_output)

[[-0.322427094 -0.453153342 -0.874035954]
 [0.976908803 0.997917175 -0.99999392]
 [0.999860227 0.999999166 -1]]


In [8]:
tf.print(yt1_output)

[[1 1 -1]
 [1 1 -1]
 [1 1 -1]]


In [9]:
(15**2018)%7

1